<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('requirements', 'RequirementsController');
	Route::get('requirements/{id}/delete', array('as' => 'admin.requirements.delete', 'uses' => 'RequirementsController@getDelete'));
	Route::get('requirements/{id}/confirm-delete', array('as' => 'admin.requirements.confirm-delete', 'uses' => 'RequirementsController@getModalDelete'));
});